# Generated by Django 6.0.3 on 2026-03-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='polls.polloption'),
        ),
    ]
