# Generated by Django 6.0.3 on 2026-03-18 21:22

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_polloption_votes_alter_poll_question_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_poll_and_voter',
        ),
        migrations.AddField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(default=polls.models.default_poll_expiration),
        ),
        migrations.AddField(
            model_name='poll',
            name='multi_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('poll', 'voter_token', 'option'), name='unique_option_vote_per_user'),
        ),
    ]
