# Generated by Codex on 2026-03-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_vote_unique_vote_per_poll_and_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expired_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_option_vote_per_user',
        ),
        migrations.RenameModel(
            old_name='Vote',
            new_name='VoteRecord',
        ),
        migrations.RenameField(
            model_name='voterecord',
            old_name='voter_token',
            new_name='device_token_hash',
        ),
        migrations.AddField(
            model_name='voterecord',
            name='voter_name',
            field=models.CharField(default='Anonymous', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='polls.polloption'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='polls.poll'),
        ),
        migrations.AddConstraint(
            model_name='voterecord',
            constraint=models.UniqueConstraint(fields=('poll', 'device_token_hash', 'option'), name='unique_option_vote_per_device'),
        ),
    ]
