# Generated by Django 5.1.6 on 2026-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_fix_device_vote_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voterecord',
            name='unique_vote_per_device_per_poll',
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['poll', 'device_token_hash'], name='polls_voter_poll_id_126613_idx'),
        ),
        migrations.AddConstraint(
            model_name='voterecord',
            constraint=models.UniqueConstraint(fields=('poll', 'option', 'device_token_hash'), name='unique_vote_per_device_per_option_per_poll'),
        ),
    ]
